# Generated by Django 2.0.1 on 2018-07-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='timeStamp',
            field=models.DateField(),
        ),
    ]
